org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.configuration-cache=true
org.gradle.caching=true

mod_java_version=21
minecraft_version=1.21.1
minecraft_version_range=[1.21,1.21.1)
neo_version=21.1.213
neo_version_range=[21.0.0-beta,)
loader_version_range=[4,)
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

mod_name=Malum
mod_id=malum
mod_version=1.9.0
mod_license=All Rights Reserved
mod_group_id=com.sammy.malum
mod_authors=Sammy Semicolon
mod_description=A dark magic mod focused on soul and spirit magic.

# Mandatory
lodestone_version=1.8.3.571
lodestone_version_range=[1.8.3,)
curios_version=9.3.1+1.21.1

# Wayward Attributes
wayward_attributes_version=1.1.30

# Iron's Spellbooks
gecko_lib_version=4.7
player_animator_version=2.0.0-alpha1+1.21
irons_spells_version=1.21-3.8.5

# KubeJS
kubejs_version=2101.7.2-build.277
rhino_version=2001.2.2-build.13

# Create
create_version = 6.0.7-117
flywheel_version = 1.0.4
flywheel_version_range = [1.0.0,2.0)
ponder_version = 1.0.56
registrate_version = MC1.21-1.3.0+62

# Misc
jei_version=19.25.0.322
fusion_version=1.1.1

imgui_version=1.86.11