modLoader = "javafml"
loaderVersion = "[43,)"
license = "All rights reserved"
[[mods]]
logoFile = "malum.png"
modId = "malum"
version = "${file.jarVersion}"
displayName = "Malum"
authors = "Sammy;"
description = '''
A dark magic mod focused on soul and spirit magic.
'''
[[dependencies.malum]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.malum]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.malum]]
modId = "lodestone"
mandatory = true
versionRange = "[1.19.2-1.4.1,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.malum]]
modId = "curios"
mandatory = true
versionRange = "[FORGE-1.19.2-5.1.1.0,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.malum]]
modId = "tetra"
mandatory = false
versionRange = "[FORGE-1.19.2,)"
ordering = "AFTER"
side = "BOTH"
