package com.sammy.malum.client.creative_tab;

import com.sammy.malum.registry.common.item.MalumItems;

public class Categories {

    public static void buildCategories() {
        MalumCreativeTabTweaks.create("spirits")
                .addItems(
                        MalumItems.SACRED_SPIRIT, MalumItems.WICKED_SPIRIT, MalumItems.ARCANE_SPIRIT, MalumItems.ELDRITCH_SPIRIT,
                        MalumItems.AERIAL_SPIRIT, MalumItems.AQUEOUS_SPIRIT, MalumItems.EARTHEN_SPIRIT, MalumItems.INFERNAL_SPIRIT,
                        MalumItems.UMBRAL_SPIRIT)
                .bake();
        MalumCreativeTabTweaks.create("miracles")
                .addItems(
                        MalumItems.ENCYCLOPEDIA_ARCANA,
                        MalumItems.ENCYCLOPEDIA_ESOTERICA,
                        MalumItems.SPIRIT_ALTAR,
                        MalumItems.RUNEWOOD_OBELISK,
                        MalumItems.BRILLIANT_OBELISK,
                        MalumItems.SPIRIT_JAR,
                        MalumItems.RUNIC_WORKBENCH,
                        MalumItems.WEAVERS_WORKBENCH,
                        MalumItems.SOUL_BRAZIER
                ).nextLine()
                .addItems(
                        MalumItems.RUNEWOOD_ITEM_PEDESTAL,
                        MalumItems.GILDED_RUNEWOOD_ITEM_PEDESTAL,
                        MalumItems.RUNEWOOD_ITEM_STAND,
                        MalumItems.GILDED_RUNEWOOD_ITEM_STAND,
                        MalumItems.TAINTED_ROCK_ITEM_PEDESTAL,
                        MalumItems.TWISTED_ROCK_ITEM_PEDESTAL,
                        MalumItems.TAINTED_ROCK_ITEM_STAND,
                        MalumItems.TWISTED_ROCK_ITEM_STAND
                ).nextLine()
                .addItems(
                        MalumItems.TUNING_FORK,
                        MalumItems.SPIRIT_CRUCIBLE,
                        MalumItems.SPIRIT_CATALYZER,
                        MalumItems.REPAIR_PYLON
                ).nextLine()
                .addItems(
                        MalumItems.TOTEMIC_STAFF,
                        MalumItems.RUNEWOOD_TOTEM_BASE,
                        MalumItems.SOULWOOD_TOTEM_BASE,
                        MalumItems.WAVEFORM_RUNEWOOD_TOTEM_BASE,
                        MalumItems.WAVEFORM_SOULWOOD_TOTEM_BASE,
                        MalumItems.ARCANA_PYLON,
                        MalumItems.RITE_ANCHOR,
                        MalumItems.RITE_UNWEAVER
                ).nextLine()
                .addItems(
                        MalumItems.WAVECHARGER,
                        MalumItems.WAVEBANKER,
                        MalumItems.WAVEMAKER,
                        MalumItems.WAVEBREAKER,
                        MalumItems.GUST_IGNITER,
                        MalumItems.WIND_TUNNEL
                )
                .bake();
        MalumCreativeTabTweaks.create("gear")
                .addItems(
                        MalumItems.CRUDE_SCYTHE,
                        MalumItems.SOULWOVEN_POUCH,
                        MalumItems.RAVENOUS_POUCH,
                        MalumItems.TOTEMIC_STAFF,
                        MalumItems.ARTIFICERS_CLAW,
                        MalumItems.TUNING_FORK,
                        MalumItems.LAMPLIGHTERS_TONGS,
                        MalumItems.CATALYST_LOBBER,
                        MalumItems.CONCENTRATED_GLUTTONY,
                        MalumItems.SPLASH_OF_GLUTTONY
                ).nextLine()
                .addItems(
                        MalumItems.SOUL_STAINED_STEEL_HELMET,
                        MalumItems.SOUL_STAINED_STEEL_CHESTPLATE,
                        MalumItems.SOUL_STAINED_STEEL_LEGGINGS,
                        MalumItems.SOUL_STAINED_STEEL_BOOTS,
                        MalumItems.SOUL_STAINED_STEEL_SWORD,
                        MalumItems.SOUL_STAINED_STEEL_PICKAXE,
                        MalumItems.SOUL_STAINED_STEEL_AXE,
                        MalumItems.SOUL_STAINED_STEEL_SHOVEL,
                        MalumItems.SOUL_STAINED_STEEL_HOE
                )
                .addItems(
                        MalumItems.SOUL_HUNTER_CLOAK,
                        MalumItems.SOUL_HUNTER_ROBE,
                        MalumItems.SOUL_HUNTER_LEGGINGS,
                        MalumItems.SOUL_HUNTER_BOOTS,
                        MalumItems.TYRVING,
                        MalumItems.SOUL_STAINED_STEEL_SCYTHE,
                        MalumItems.SOUL_STAINED_STEEL_KNIFE,
                        MalumItems.SPELLWEAVING_PICKAXE,
                        MalumItems.SPELLWEAVING_AXE
                ).nextLine()
                .addItems(
                        MalumItems.MALIGNANT_STRONGHOLD_HELMET,
                        MalumItems.MALIGNANT_STRONGHOLD_CHESTPLATE,
                        MalumItems.MALIGNANT_STRONGHOLD_LEGGINGS,
                        MalumItems.MALIGNANT_STRONGHOLD_BOOTS,
                        MalumItems.WEIGHT_OF_WORLDS,
                        MalumItems.EDGE_OF_DELIVERANCE,
                        MalumItems.SUNDERING_ANCHOR
                ).nextLine()
                .addItems(
                        MalumItems.MNEMONIC_HEX_STAFF,
                        MalumItems.EROSION_SCEPTER,
                        MalumItems.UNWINDING_CHAOS
                )
                .bake();
        MalumCreativeTabTweaks.create("trinkets")
                .addItems(
                        MalumItems.GILDED_RING,
                        MalumItems.GILDED_BELT,
                        MalumItems.ORNATE_RING,
                        MalumItems.ORNATE_NECKLACE
                ).nextLine()
                .addItems(
                        MalumItems.RUNIC_BROOCH,
                        MalumItems.ELABORATE_BROOCH,
                        MalumItems.GLASS_BROOCH,
                        MalumItems.GLUTTONOUS_BROOCH
                ).nextLine()
                .addItems(
                        MalumItems.RING_OF_ESOTERIC_SPOILS,
                        MalumItems.RING_OF_THE_RISING_EDGE,
                        MalumItems.RING_OF_THE_HOWLING_MAELSTROM,
                        MalumItems.RING_OF_CURATIVE_TALENT,
                        MalumItems.RING_OF_ARCANE_PROWESS,
                        MalumItems.RING_OF_MANAWEAVING,
                        MalumItems.RING_OF_ALCHEMICAL_MASTERY,
                        MalumItems.RING_OF_DESPERATE_VORACITY,
                        MalumItems.RING_OF_THE_HOARDER,
                        MalumItems.RING_OF_THE_DEMOLITIONIST
                ).nextLine()
                .addItems(
                        MalumItems.NECKLACE_OF_THE_MYSTIC_MIRROR,
                        MalumItems.NECKLACE_OF_THE_NARROW_EDGE,
                        MalumItems.NECKLACE_OF_BLISSFUL_HARMONY
                ).nextLine()
                .addItems(
                        MalumItems.BELT_OF_THE_STARVED,
                        MalumItems.BELT_OF_THE_PROSPECTOR,
                        MalumItems.BELT_OF_THE_MAGEBANE
                ).nextLine()
                .addItems(
                        MalumItems.RING_OF_THE_ENDLESS_WELL,
                        MalumItems.RING_OF_ECHOING_ARCANA,
                        MalumItems.RING_OF_GROWING_FLESH,
                        MalumItems.RING_OF_GRUESOME_CONCENTRATION,
                        MalumItems.NECKLACE_OF_THE_HIDDEN_BLADE,
                        MalumItems.NECKLACE_OF_THE_WATCHER,
                        MalumItems.BELT_OF_THE_LIMITLESS
                ).nextLine()
                .addItems(
                        MalumItems.RUNE_OF_VITALITY,
                        MalumItems.RUNE_OF_CULLING,
                        MalumItems.RUNE_OF_REINFORCEMENT,
                        MalumItems.RUNE_OF_VOLATILE_DISTORTION,
                        MalumItems.RUNE_OF_DEXTERITY,
                        MalumItems.RUNE_OF_AILMENT_CLEANSING,
                        MalumItems.RUNE_OF_PROTECTION,
                        MalumItems.RUNE_OF_SCORCHING
                ).nextLine()
                .addItems(
                        MalumItems.RUNE_OF_HOWLING_GALE,
                        MalumItems.RUNE_OF_FLOWING_GRASP,
                        MalumItems.RUNE_OF_STONE_WARD,
                        MalumItems.RUNE_OF_BURNING_FERVOR,
                        MalumItems.RUNE_OF_SKY_TETHER,
                        MalumItems.RUNE_OF_GOOD_TIDES,
                        MalumItems.RUNE_OF_OAKEN_MIGHT,
                        MalumItems.RUNE_OF_FIERY_EMBRACE
                ).nextLine()
                .addItems(
                        MalumItems.RUNE_OF_BOLSTERING,
                        MalumItems.RUNE_OF_RADIAL_EMPOWERMENT,
                        MalumItems.RUNE_OF_SPELL_MASTERY,
                        MalumItems.RUNE_OF_HERESY,
                        MalumItems.RUNE_OF_UNNATURAL_STAMINA,
                        MalumItems.RUNE_OF_TWINNED_DURATION,
                        MalumItems.RUNE_OF_INDOMITABILITY,
                        MalumItems.RUNE_OF_IGNEOUS_SOLACE
                )
                .bake();
        MalumCreativeTabTweaks.create("materials")
                .addItems(
                        MalumItems.BLOCK_OF_ROTTING_ESSENCE,
                        MalumItems.BLOCK_OF_GRIM_TALC,
                        MalumItems.BLOCK_OF_ASTRAL_WEAVE,
                        MalumItems.BLOCK_OF_WARP_FLUX,
                        MalumItems.ROTTING_ESSENCE,
                        MalumItems.GRIM_TALC,
                        MalumItems.ASTRAL_WEAVE,
                        MalumItems.WARP_FLUX
                ).nextLine()
                .addItems(
                        MalumItems.BLOCK_OF_HEX_ASH,
                        MalumItems.BLOCK_OF_LIVING_FLESH,
                        MalumItems.BLOCK_OF_ALCHEMICAL_CALX,
                        MalumItems.HEX_ASH,
                        MalumItems.LIVING_FLESH,
                        MalumItems.ALCHEMICAL_CALX
                ).nextLine()
                .addItems(
                        MalumItems.SOULWOVEN_SILK,
                        MalumItems.PARACAUSAL_FLAME,
                        MalumItems.CONVOLUTED_LENS,
                        MalumItems.MIMICRY_RELAY,
                        MalumItems.POPPET,
                        MalumItems.IMITATION_FLESH,
                        MalumItems.IMITATION_HEART
                ).nextLine()
                .addItems(
                        MalumItems.ANOMALOUS_DESIGN,
                        MalumItems.COMPLETE_DESIGN,
                        MalumItems.FUSED_CONSCIOUSNESS
                ).nextLine()
                .addItems(
                        MalumItems.BLOCK_OF_NULL_SLATE,
                        MalumItems.BLOCK_OF_VOID_SALTS,
                        MalumItems.BLOCK_OF_MNEMONIC_FRAGMENT,
                        MalumItems.BLOCK_OF_AURIC_EMBERS,
                        MalumItems.NULL_SLATE,
                        MalumItems.VOID_SALTS,
                        MalumItems.MNEMONIC_FRAGMENT,
                        MalumItems.AURIC_EMBERS
                ).nextLine()
                .addItems(
                        MalumItems.BLOCK_OF_SOUL_STAINED_STEEL,
                        MalumItems.SOUL_STAINED_STEEL_INGOT,
                        MalumItems.SOUL_STAINED_STEEL_PLATING,
                        MalumItems.SOUL_STAINED_STEEL_NUGGET,
                        MalumItems.BLOCK_OF_HALLOWED_GOLD,
                        MalumItems.HALLOWED_GOLD_INGOT,
                        MalumItems.HALLOWED_GOLD_NUGGET
                ).nextLine()
                .addItems(
                        MalumItems.BLOCK_OF_MALIGNANT_LEAD,
                        MalumItems.BLOCK_OF_MALIGNANT_PEWTER,
                        MalumItems.MALIGNANT_LEAD,
                        MalumItems.MALIGNANT_PEWTER_INGOT,
                        MalumItems.MALIGNANT_PEWTER_PLATING,
                        MalumItems.MALIGNANT_PEWTER_NUGGET
                ).bake();
        MalumCreativeTabTweaks.create("ether")
                .addItems(
                        MalumItems.ETHER,
                        MalumItems.IRIDESCENT_ETHER
                ).nextLine()
                .addItems(
                        MalumItems.ETHER_TORCH,
                        MalumItems.IRIDESCENT_ETHER_TORCH
                ).nextLine()
                .addItems(
                        MalumItems.TAINTED_ETHER_BRAZIER,
                        MalumItems.TWISTED_ETHER_BRAZIER,
                        MalumItems.DROSS_ETHER_BRAZIER
                ).nextLine()
                .addItems(
                        MalumItems.TAINTED_IRIDESCENT_ETHER_BRAZIER,
                        MalumItems.TWISTED_IRIDESCENT_ETHER_BRAZIER,
                        MalumItems.DROSS_IRIDESCENT_ETHER_BRAZIER
                ).nextLine()
                .addItems(
                        MalumItems.TAINTED_ETHER_CRESSET,
                        MalumItems.TWISTED_ETHER_CRESSET,
                        MalumItems.DROSS_ETHER_CRESSET
                ).nextLine()
                .addItems(
                        MalumItems.TAINTED_IRIDESCENT_ETHER_CRESSET,
                        MalumItems.TWISTED_IRIDESCENT_ETHER_CRESSET,
                        MalumItems.DROSS_IRIDESCENT_ETHER_CRESSET
                )
                .bake();
        MalumCreativeTabTweaks.create("metallurgy")
                .addItems(MalumItems.IRON_IMPETUS, MalumItems.FRACTURED_IRON_IMPETUS, MalumItems.IRON_NODE)
                .addItems(MalumItems.COPPER_IMPETUS, MalumItems.FRACTURED_COPPER_IMPETUS, MalumItems.COPPER_NODE)
                .addItems(MalumItems.GOLD_IMPETUS, MalumItems.FRACTURED_GOLD_IMPETUS, MalumItems.GOLD_NODE)
                .addItems(MalumItems.ALUMINUM_IMPETUS, MalumItems.FRACTURED_ALUMINUM_IMPETUS, MalumItems.ALUMINUM_NODE)
                .addItems(MalumItems.NICKEL_IMPETUS, MalumItems.FRACTURED_NICKEL_IMPETUS, MalumItems.NICKEL_NODE)
                .addItems(MalumItems.SILVER_IMPETUS, MalumItems.FRACTURED_SILVER_IMPETUS, MalumItems.SILVER_NODE)
                .addItems(MalumItems.TIN_IMPETUS, MalumItems.FRACTURED_TIN_IMPETUS, MalumItems.TIN_NODE)
                .addItems(MalumItems.ZINC_IMPETUS, MalumItems.FRACTURED_ZINC_IMPETUS, MalumItems.ZINC_NODE)
                .addItems(MalumItems.OSMIUM_IMPETUS, MalumItems.FRACTURED_OSMIUM_IMPETUS, MalumItems.OSMIUM_NODE)
                .addItems(MalumItems.LEAD_IMPETUS, MalumItems.FRACTURED_LEAD_IMPETUS, MalumItems.LEAD_NODE)
                .addItems(MalumItems.URANIUM_IMPETUS, MalumItems.FRACTURED_URANIUM_IMPETUS, MalumItems.URANIUM_NODE)
                .addItems(MalumItems.COBALT_IMPETUS, MalumItems.FRACTURED_COBALT_IMPETUS, MalumItems.COBALT_NODE)
                .addItems(MalumItems.ZEPHYR_IMPETUS, MalumItems.FRACTURED_ZEPHYR_IMPETUS)
                .addItems(MalumItems.ALCHEMICAL_IMPETUS, MalumItems.FRACTURED_ALCHEMICAL_IMPETUS)
                .bake();
        MalumCreativeTabTweaks.create("augments")
                .addItems(
                        MalumItems.MENDING_DIFFUSER,
                        MalumItems.IMPURITY_STABILIZER,
                        MalumItems.SHIELDING_APPARATUS,
                        MalumItems.WARPING_ENGINE,
                        MalumItems.ACCELERATING_INLAY,
                        MalumItems.PRISMATIC_FOCUS_LENS,
                        MalumItems.BLAZING_DIODE,
                        MalumItems.INTRICATE_ASSEMBLY
                ).nextLine()
                .addItems(
                        MalumItems.SYMPATHY_DRIVE,
                        MalumItems.SUSPICIOUS_DEVICE,
                        MalumItems.CAUSTIC_CATALYST,
                        MalumItems.RESONANCE_TUNER
                ).nextLine()
                .addItems(
                        MalumItems.STELLAR_MECHANISM
                )
                .bake();
        MalumCreativeTabTweaks.create("ores")
                .addItems(
                        MalumItems.BLOCK_OF_SOULSTONE, MalumItems.BLOCK_OF_RAW_SOULSTONE, MalumItems.DEEPSLATE_SOULSTONE_ORE, MalumItems.SOULSTONE_ORE,
                        MalumItems.RAW_SOULSTONE, MalumItems.CRUSHED_SOULSTONE, MalumItems.REFINED_SOULSTONE
                ).nextLine()
                .addItems(
                        MalumItems.BLOCK_OF_BRILLIANCE, MalumItems.BRILLIANT_DEEPSLATE, MalumItems.BRILLIANT_STONE, MalumItems.RAW_BRILLIANCE,
                        MalumItems.CRUSHED_BRILLIANCE, MalumItems.REFINED_BRILLIANCE
                ).nextLine()
                .addItems(
                        MalumItems.BLOCK_OF_BLAZING_QUARTZ, MalumItems.BLAZING_QUARTZ_ORE,
                        MalumItems.BLAZING_QUARTZ
                )
                .addItems(
                        MalumItems.DEEPSLATE_QUARTZ_ORE, MalumItems.NATURAL_QUARTZ_ORE,
                        MalumItems.NATURAL_QUARTZ
                ).nextLine()
                .addItems(
                        MalumItems.BLOCK_OF_CTHONIC_GOLD, MalumItems.CTHONIC_GOLD_ORE,
                        MalumItems.CTHONIC_GOLD, MalumItems.CTHONIC_GOLD_FRAGMENT
                )
                .bake();
        MalumCreativeTabTweaks.create("soulstuff")
                .addItems(
                        MalumItems.SACRED_SPIRITED_GLASS,
                        MalumItems.WICKED_SPIRITED_GLASS,
                        MalumItems.ARCANE_SPIRITED_GLASS,
                        MalumItems.ELDRITCH_SPIRITED_GLASS,
                        MalumItems.AERIAL_SPIRITED_GLASS,
                        MalumItems.AQUEOUS_SPIRITED_GLASS,
                        MalumItems.EARTHEN_SPIRITED_GLASS,
                        MalumItems.INFERNAL_SPIRITED_GLASS,
                        MalumItems.NULL_SPIRITED_GLASS
                ).nextLine()
                .addItems(
                        MalumItems.SACRED_VARNISHED_TERRACOTTA,
                        MalumItems.WICKED_VARNISHED_TERRACOTTA,
                        MalumItems.ARCANE_VARNISHED_TERRACOTTA,
                        MalumItems.ELDRITCH_VARNISHED_TERRACOTTA,
                        MalumItems.AERIAL_VARNISHED_TERRACOTTA,
                        MalumItems.AQUEOUS_VARNISHED_TERRACOTTA,
                        MalumItems.EARTHEN_VARNISHED_TERRACOTTA,
                        MalumItems.INFERNAL_VARNISHED_TERRACOTTA,
                        MalumItems.NULL_VARNISHED_TERRACOTTA
                ).nextLine()
                .addItems(
                        MalumItems.SOULWOVEN_BANNER
                )
                .bake();
        MalumCreativeTabTweaks.create("runewood")
                .addItems(
                        MalumItems.RUNEWOOD_SAPLING,
                        MalumItems.AZURE_RUNEWOOD_SAPLING,
                        MalumItems.RUNIC_SAP,
                        MalumItems.RUNIC_SAPBALL,
                        MalumItems.RUNEWOOD_LEAVES,
                        MalumItems.AZURE_RUNEWOOD_LEAVES,
                        MalumItems.HANGING_RUNEWOOD_LEAVES,
                        MalumItems.HANGING_AZURE_RUNEWOOD_LEAVES
                ).nextLine()
                .addItems(
                        MalumItems.RUNEWOOD_LOG,
                        MalumItems.STRIPPED_RUNEWOOD_LOG,
                        MalumItems.RUNEWOOD,
                        MalumItems.STRIPPED_RUNEWOOD,
                        MalumItems.EXPOSED_RUNEWOOD_LOG,
                        MalumItems.REVEALED_RUNEWOOD_LOG
                ).nextLine()
                .addItems(
                        MalumItems.RUNEWOOD_BOARDS,
                        MalumItems.VERTICAL_RUNEWOOD_BOARDS,
                        MalumItems.RUNEWOOD_PLANKS,
                        MalumItems.VERTICAL_RUNEWOOD_PLANKS,
                        MalumItems.RUNEWOOD_TILES,
                        MalumItems.RUSTIC_RUNEWOOD_PLANKS,
                        MalumItems.VERTICAL_RUSTIC_RUNEWOOD_PLANKS,
                        MalumItems.RUSTIC_RUNEWOOD_TILES
                ).nextLine()
                .addItems(
                        MalumItems.RUNEWOOD_BOARDS_SLAB,
                        MalumItems.VERTICAL_RUNEWOOD_BOARDS_SLAB,
                        MalumItems.RUNEWOOD_PLANKS_SLAB,
                        MalumItems.VERTICAL_RUNEWOOD_PLANKS_SLAB,
                        MalumItems.RUNEWOOD_TILES_SLAB,
                        MalumItems.RUSTIC_RUNEWOOD_PLANKS_SLAB,
                        MalumItems.VERTICAL_RUSTIC_RUNEWOOD_PLANKS_SLAB,
                        MalumItems.RUSTIC_RUNEWOOD_TILES_SLAB
                ).nextLine()
                .addItems(
                        MalumItems.RUNEWOOD_BOARDS_STAIRS,
                        MalumItems.VERTICAL_RUNEWOOD_BOARDS_STAIRS,
                        MalumItems.RUNEWOOD_PLANKS_STAIRS,
                        MalumItems.VERTICAL_RUNEWOOD_PLANKS_STAIRS,
                        MalumItems.RUNEWOOD_TILES_STAIRS,
                        MalumItems.RUSTIC_RUNEWOOD_PLANKS_STAIRS,
                        MalumItems.VERTICAL_RUSTIC_RUNEWOOD_PLANKS_STAIRS,
                        MalumItems.RUSTIC_RUNEWOOD_TILES_STAIRS
                ).nextLine()
                .addItems(
                        MalumItems.RUNEWOOD_PANEL,
                        MalumItems.CUT_RUNEWOOD_PLANKS,
                        MalumItems.RUNEWOOD_BEAM,
                        MalumItems.RUNEWOOD_ITEM_PEDESTAL,
                        MalumItems.GILDED_RUNEWOOD_ITEM_PEDESTAL,
                        MalumItems.RUNEWOOD_ITEM_STAND,
                        MalumItems.GILDED_RUNEWOOD_ITEM_STAND
                ).nextLine()
                .addItems(
                        MalumItems.RUNEWOOD_DOOR,
                        MalumItems.BOLTED_RUNEWOOD_DOOR,
                        MalumItems.RUNEWOOD_TRAPDOOR,
                        MalumItems.BOLTED_RUNEWOOD_TRAPDOOR,
                        MalumItems.RUNEWOOD_BOARDS_DOOR,
                        MalumItems.BOLTED_RUNEWOOD_BOARDS_DOOR,
                        MalumItems.RUNEWOOD_BOARDS_TRAPDOOR,
                        MalumItems.BOLTED_RUNEWOOD_BOARDS_TRAPDOOR
                ).nextLine()
                .addItems(
                        MalumItems.RUNEWOOD_BOARDS_WALL,
                        MalumItems.RUNEWOOD_FENCE,
                        MalumItems.RUNEWOOD_FENCE_GATE,
                        MalumItems.RUNEWOOD_SIGN,
                        MalumItems.RUNEWOOD_BOAT,
                        MalumItems.RUNEWOOD_CHEST_BOAT
                )
                .bake();
        MalumCreativeTabTweaks.create("soulwood")
                .addItems(
                        MalumItems.SOULWOOD_SAPLING,
                        MalumItems.CURSED_SAP,
                        MalumItems.CURSED_SAPBALL,
                        MalumItems.SOULWOOD_LEAVES,
                        MalumItems.HANGING_SOULWOOD_LEAVES
                ).nextLine()
                .addItems(
                        MalumItems.SOULWOOD_LOG,
                        MalumItems.STRIPPED_SOULWOOD_LOG,
                        MalumItems.SOULWOOD,
                        MalumItems.STRIPPED_SOULWOOD,
                        MalumItems.EXPOSED_SOULWOOD_LOG,
                        MalumItems.REVEALED_SOULWOOD_LOG,
                        MalumItems.BLIGHTED_SOULWOOD
                ).nextLine()
                .addItems(
                        MalumItems.SOULWOOD_BOARDS,
                        MalumItems.VERTICAL_SOULWOOD_BOARDS,
                        MalumItems.SOULWOOD_PLANKS,
                        MalumItems.VERTICAL_SOULWOOD_PLANKS,
                        MalumItems.SOULWOOD_TILES,
                        MalumItems.RUSTIC_SOULWOOD_PLANKS,
                        MalumItems.VERTICAL_RUSTIC_SOULWOOD_PLANKS,
                        MalumItems.RUSTIC_SOULWOOD_TILES
                ).nextLine()
                .addItems(
                        MalumItems.SOULWOOD_BOARDS_SLAB,
                        MalumItems.VERTICAL_SOULWOOD_BOARDS_SLAB,
                        MalumItems.SOULWOOD_PLANKS_SLAB,
                        MalumItems.VERTICAL_SOULWOOD_PLANKS_SLAB,
                        MalumItems.SOULWOOD_TILES_SLAB,
                        MalumItems.RUSTIC_SOULWOOD_PLANKS_SLAB,
                        MalumItems.VERTICAL_RUSTIC_SOULWOOD_PLANKS_SLAB,
                        MalumItems.RUSTIC_SOULWOOD_TILES_SLAB
                ).nextLine()
                .addItems(
                        MalumItems.SOULWOOD_BOARDS_STAIRS,
                        MalumItems.VERTICAL_SOULWOOD_BOARDS_STAIRS,
                        MalumItems.SOULWOOD_PLANKS_STAIRS,
                        MalumItems.VERTICAL_SOULWOOD_PLANKS_STAIRS,
                        MalumItems.SOULWOOD_TILES_STAIRS,
                        MalumItems.RUSTIC_SOULWOOD_PLANKS_STAIRS,
                        MalumItems.VERTICAL_RUSTIC_SOULWOOD_PLANKS_STAIRS,
                        MalumItems.RUSTIC_SOULWOOD_TILES_STAIRS
                ).nextLine()
                .addItems(
                        MalumItems.SOULWOOD_PANEL,
                        MalumItems.CUT_SOULWOOD_PLANKS,
                        MalumItems.SOULWOOD_BEAM,
                        MalumItems.SOULWOOD_ITEM_PEDESTAL,
                        MalumItems.ORNATE_SOULWOOD_ITEM_PEDESTAL,
                        MalumItems.SOULWOOD_ITEM_STAND,
                        MalumItems.ORNATE_SOULWOOD_ITEM_STAND
                ).nextLine()
                .addItems(
                        MalumItems.SOULWOOD_DOOR,
                        MalumItems.BOLTED_SOULWOOD_DOOR,
                        MalumItems.SOULWOOD_TRAPDOOR,
                        MalumItems.BOLTED_SOULWOOD_TRAPDOOR,
                        MalumItems.SOULWOOD_BOARDS_DOOR,
                        MalumItems.BOLTED_SOULWOOD_BOARDS_DOOR,
                        MalumItems.SOULWOOD_BOARDS_TRAPDOOR,
                        MalumItems.BOLTED_SOULWOOD_BOARDS_TRAPDOOR
                ).nextLine()
                .addItems(
                        MalumItems.SOULWOOD_BUTTON,
                        MalumItems.SOULWOOD_PRESSURE_PLATE,
                        MalumItems.SOULWOOD_BOARDS_WALL,
                        MalumItems.SOULWOOD_FENCE,
                        MalumItems.SOULWOOD_FENCE_GATE,
                        MalumItems.SOULWOOD_SIGN,
                        MalumItems.SOULWOOD_BOAT,
                        MalumItems.SOULWOOD_CHEST_BOAT
                )
                .bake();
        MalumCreativeTabTweaks.create("blight")
                .addItems(
                        MalumItems.BLIGHTED_SOULWOOD,
                        MalumItems.COLUMNAR_BLIGHT,
                        MalumItems.BLIGHTED_EARTH,
                        MalumItems.BLIGHT,
                        MalumItems.BLIGHTED_GUNK,
                        MalumItems.BLIGHTPEARL,
                        MalumItems.BLIGHTROOT
                ).nextLine()
                .addItems(
                        MalumItems.SCARSTONE,
                        MalumItems.LARGE_STRANGE_CRYSTAL,
                        MalumItems.STRANGE_CRYSTAL,
                        MalumItems.STRANGEROOT
                )
                .bake();

        MalumCreativeTabTweaks.create("tainted_rock")
                .addItems(
                        MalumItems.TAINTED_ROCK,
                        MalumItems.POLISHED_TAINTED_ROCK,
                        MalumItems.TAINTED_ROCK_BRICKS,
                        MalumItems.TAINTED_ROCK_TILES,
                        MalumItems.TAINTED_ROCK_MOSAIC
                ).nextLine()
                .addItems(
                        MalumItems.TAINTED_ROCK_STAIRS,
                        MalumItems.POLISHED_TAINTED_ROCK_STAIRS,
                        MalumItems.TAINTED_ROCK_BRICKS_STAIRS,
                        MalumItems.TAINTED_ROCK_TILES_STAIRS,
                        MalumItems.TAINTED_ROCK_MOSAIC_STAIRS
                ).nextLine()
                .addItems(
                        MalumItems.TAINTED_ROCK_SLAB,
                        MalumItems.POLISHED_TAINTED_ROCK_SLAB,
                        MalumItems.TAINTED_ROCK_BRICKS_SLAB,
                        MalumItems.TAINTED_ROCK_TILES_SLAB,
                        MalumItems.TAINTED_ROCK_MOSAIC_SLAB
                ).nextLine()
                .addItems(
                        MalumItems.TAINTED_ROCK_WALL,
                        MalumItems.POLISHED_TAINTED_ROCK_WALL,
                        MalumItems.TAINTED_ROCK_BRICKS_WALL,
                        MalumItems.TAINTED_ROCK_TILES_WALL,
                        MalumItems.TAINTED_ROCK_MOSAIC_WALL
                ).nextLine()
                .addItems(
                        MalumItems.TAINTED_ROCK_COLUMN,
                        MalumItems.CUT_TAINTED_ROCK,
                        MalumItems.CHISELED_TAINTED_ROCK
                )
                .addItems(
                        MalumItems.TAINTED_ROCK_PRESSURE_PLATE,
                        MalumItems.TAINTED_ROCK_BUTTON,
                        MalumItems.TAINTED_ROCK_ITEM_STAND,
                        MalumItems.TAINTED_ROCK_ITEM_PEDESTAL
                )
                .bake();
        MalumCreativeTabTweaks.create("twisted_rock")
                .addItems(
                        MalumItems.TWISTED_ROCK,
                        MalumItems.POLISHED_TWISTED_ROCK,
                        MalumItems.TWISTED_ROCK_BRICKS,
                        MalumItems.TWISTED_ROCK_TILES,
                        MalumItems.TWISTED_ROCK_MOSAIC
                ).nextLine()
                .addItems(
                        MalumItems.TWISTED_ROCK_STAIRS,
                        MalumItems.POLISHED_TWISTED_ROCK_STAIRS,
                        MalumItems.TWISTED_ROCK_BRICKS_STAIRS,
                        MalumItems.TWISTED_ROCK_TILES_STAIRS,
                        MalumItems.TWISTED_ROCK_MOSAIC_STAIRS
                ).nextLine()
                .addItems(
                        MalumItems.TWISTED_ROCK_SLAB,
                        MalumItems.POLISHED_TWISTED_ROCK_SLAB,
                        MalumItems.TWISTED_ROCK_BRICKS_SLAB,
                        MalumItems.TWISTED_ROCK_TILES_SLAB,
                        MalumItems.TWISTED_ROCK_MOSAIC_SLAB
                ).nextLine()
                .addItems(
                        MalumItems.TWISTED_ROCK_WALL,
                        MalumItems.POLISHED_TWISTED_ROCK_WALL,
                        MalumItems.TWISTED_ROCK_BRICKS_WALL,
                        MalumItems.TWISTED_ROCK_TILES_WALL,
                        MalumItems.TWISTED_ROCK_MOSAIC_WALL
                ).nextLine()
                .addItems(
                        MalumItems.TWISTED_ROCK_COLUMN,
                        MalumItems.CUT_TWISTED_ROCK,
                        MalumItems.CHISELED_TWISTED_ROCK
                )
                .addItems(
                        MalumItems.TWISTED_ROCK_PRESSURE_PLATE,
                        MalumItems.TWISTED_ROCK_BUTTON,
                        MalumItems.TWISTED_ROCK_ITEM_STAND,
                        MalumItems.TWISTED_ROCK_ITEM_PEDESTAL
                )
                .bake();
        MalumCreativeTabTweaks.create("dross_stone")
                .addItems(
                        MalumItems.DROSS_STONE,
                        MalumItems.POLISHED_DROSS_STONE,
                        MalumItems.DROSS_STONE_BRICKS,
                        MalumItems.DROSS_STONE_TILES,
                        MalumItems.DROSS_STONE_MOSAIC,
                        MalumItems.GRAY_DROSS_TILES,
                        MalumItems.DARK_DROSS_TILES
                ).nextLine()
                .addItems(
                        MalumItems.DROSS_STONE_STAIRS,
                        MalumItems.POLISHED_DROSS_STONE_STAIRS,
                        MalumItems.DROSS_STONE_BRICKS_STAIRS,
                        MalumItems.DROSS_STONE_TILES_STAIRS,
                        MalumItems.DROSS_STONE_MOSAIC_STAIRS,
                        MalumItems.GRAY_DROSS_TILES_STAIRS,
                        MalumItems.DARK_DROSS_TILES_STAIRS
                ).nextLine()
                .addItems(
                        MalumItems.DROSS_STONE_SLAB,
                        MalumItems.POLISHED_DROSS_STONE_SLAB,
                        MalumItems.DROSS_STONE_BRICKS_SLAB,
                        MalumItems.DROSS_STONE_TILES_SLAB,
                        MalumItems.DROSS_STONE_MOSAIC_SLAB,
                        MalumItems.GRAY_DROSS_TILES_SLAB,
                        MalumItems.DARK_DROSS_TILES_SLAB
                ).nextLine()
                .addItems(
                        MalumItems.DROSS_STONE_WALL,
                        MalumItems.POLISHED_DROSS_STONE_WALL,
                        MalumItems.DROSS_STONE_BRICKS_WALL,
                        MalumItems.DROSS_STONE_TILES_WALL,
                        MalumItems.DROSS_STONE_MOSAIC_WALL,
                        MalumItems.GRAY_DROSS_TILES_WALL,
                        MalumItems.DARK_DROSS_TILES_WALL
                ).nextLine()
                .addItems(
                        MalumItems.DROSS_STONE_COLUMN,
                        MalumItems.CUT_DROSS_STONE,
                        MalumItems.CHISELED_DROSS_STONE
                )
                .addItems(
                        MalumItems.DROSS_STONE_PRESSURE_PLATE,
                        MalumItems.DROSS_STONE_BUTTON,
                        MalumItems.DROSS_STONE_ITEM_STAND,
                        MalumItems.DROSS_STONE_ITEM_PEDESTAL
                )
                .bake();
    }
}